
import "./globals.css";
import "public/ck-editor.css";
import Providers from "../_provider/providers";
import Alert from "@/components/front/common/modal/Alert";
import Confirm from "@/components/front/common/modal/Confirm";
import 'dayjs/locale/ko'; // load on demand
import dayjs from 'dayjs';
dayjs.locale('ko'); // use Spanish locale globally

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Providers>
            {children}
            <Alert />
            <Confirm />
        </Providers>
        </body>
        </html>
    );
}
